### ISSUE TITLE
Update links in README

### ISSUE THREAD

**Issue by Falco20019** [IBM/qiskit-openqasm#1]
The paths in the Readme lead to dead links. Please update.

https://github.com/IBMQuantum/QASM/tree/master/spec ->
https://github.com/IBM/qiskit-openqasm/tree/master/spec

https://github.com/IBMQuantum/QASM/tree/master/examples ->
https://github.com/IBM/qiskit-openqasm/tree/master/examples

**Comment by jaygambetta** [comment]
Thanks Falco I just fixed this
