### ISSUE TITLE
Is the CU1 gate in openqasm correct? 

### ISSUE THREAD

**Issue by lpxz** [IBM/qiskit-openqasm#2]
Hi,

in page 11 of openqasm specification:

a is used for control the rotation of b, so a should not be changed.

However, in the implementation, a is updated in the first statement.

gate cu1(lambda) a,b
{

  u1(lambda/2) a;
  cx a,b;
  u1(-lambda/2) b;

                

            Thanks
Peng

**Comment by jaygambetta** [comment]
Yes the specification is correct just not explained clearly in the document and we are fixing this. The cu1 we give is the gate Diag(1,1,1,exp(ilambda)) not control-rz(theta) = Diag(1,1,exp(-ilambda/2), exp(i lambda/2)).

**Comment by jaygambetta** [comment]
@lpxz We have closed this issue.  Please have a look at the document and updated qelib1.inc. If there is still any confusion please open another issue.
