### ISSUE TITLE
Algorithms by the community

### ISSUE THREAD

**Issue by sensor1** [IBM/qiskit-openqasm#4]
Dear IBM quantum team,

A zip file with quantum circuits from the IBM quantum experience community is attached. It would be great if some circuits can be merged with examples.

Thanks, Bram (user sensor1)
[qasm_circuits.zip](https://github.com/IBM/qiskit-openqasm/files/992531/qasm_circuits.zip)

**Comment by adcorcol** [comment]
@sensor1  Added a few of the examples after minor bug fixing - will go through the rest shortly

**Comment by jaygambetta** [comment]
Thanks @adcorcol and @sensor1 if there are more lets keep adding them. I will close this comment since we have added them to the repository
