### ISSUE TITLE
Small typo in a example file

### ISSUE THREAD

**Issue by YuKill** [IBM/qiskit-openqasm#7]
It seems that there is a small typo on the first line of the Deutsch Algorithm.
In the first line we have:
`\\Implementation of Deutsch algorithm with two qubits for f(x)=x`
shouldn't it be:
`//Implementation of Deutsch algorithm with two qubits for f(x)=x`
i.e. instead of the backslash, a normal slash!?

**Comment by awcross1** [comment]
Yes, thanks! Resolved by 707877f8254e276743cb2981b74a560fa5f1c3e9 from Eric Sabo
